### ISSUE TITLE
API to reload Assessment responses on page load

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/djaopsp#158]
On URL /app/steve-shop/info/sustainability-boxes-and-enclosures/the-assessment-process-is-rigorous/

We need a back button (see comment below). A solution seems to be to embed or disguise the breadcrumb trail as back button.

Comment sent by a supplier that provided feedback after taking the "Assessment", which confirms we need some form of 'back' button that also refreshes the Assessment page on back navigation to it such that a response is not lost as the below supplier experienced:
•	Navigation from best practice guidance screens back to assessment - Comment: When I clicked into the guidance for any given question and used the back button to navigate back to the assessment, my responses would be lost and would need re-entered. This is a frustrating system glitch.

**Comment by smirolo** [comment]
The self-assessment answers are loaded as part of the HTML request. When clicking on the browser back button, the browser will serve the locally cached version of the page instead of requesting it from the server. As a result, answers seems to have been lost. Loading answers through an API request might work.
Relabelling the breadcrumbs to "Back" is a workaround to incentive users to click on the page instead of the browser menubar.

**Comment by smirolo** [comment]
The code for the html page is in `views/assessments.py`. The API code is in `api/assessments.py`.
