### ISSUE TITLE
UI updates on top-level assessment page

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaopsp#350]
![Screen Shot 2020-09-18 at 9 58 49 AM](https://user-images.githubusercontent.com/3732869/93639200-7b35c000-f9ad-11ea-8e31-7fcb25883c65.png)

- "Created" should be changed to "Last updated at", even if the field in the json response is called 'created_at'.

User feedback:
- It is unclear where to click next on this screen. Add a button "Continue" in the assessment card?
- It is unclear what "Archive" means. Should it be "Delete"?

- Add number of answered (required and not required) questions vs total questions?

**Comment by quiaro** [comment]
*Fixed by #351*
- "Created" should be changed to "Last updated at"
- Make next step more intuitive by adding animation
- Show delete button for assessment until it is frozen

*Pending*
- Add number of answered (required and not required) questions vs total questions? @smirolo why would it be important for users to see information about the questions at this level? The goal of this navigation is to guide users to the section that is most relevant to them so none of the question information is being fetched/provided at this level. Pulling this information will make the navigation take longer to load. Do you think it's worth the tradeoff?

**Comment by quiaro** [comment]
@smirolo Waiting on feedback ☝️

**Comment by smirolo** [comment]
The idea of the number of questions answered is to hint between an active assessment being updated and one that was abandoned. It does happen that a user selects an industry segment, answers one question, then decides to respond on a different industry segment, leaving the abandoned segment "active".
At the top level (before this screen), it is not straightforward to identify being-updated active and abandoned active. Maybe if the "delete/reset" button is prominent it will remove the issue...
I somehow feel that in-progress is not enough and we should indicate how far along the assessment is but it is not a make or break decision at this point. "number of questions answered" could be an enhancement later on if necessary.
